module ApiConstants
  PRODUCT_VOTE_UP = 'PRODUCT_VOTE_UP'
  PRODUCT_VOTE_DOWN = 'PRODUCT_VOTE_DOWN'
  BRAND_FOLLOW = 'BRAND_FOLLOW'
  BRAND_UNFOLLOW = 'BRAND_UNFOLLOW'
  MISSING_LOCATION = "MISSING_LOCATION"
end