# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

smtp_dev_test: &smtp_dev_test
  smtp_settings_address_user_name: "fathallah.houssem@gmail.com"
  smtp_settings_address_password: "Google0902__GO"

business_configure_dev_test: &business_configure_dev_test
  business_requests_mail_alert: fathallah.houssem@gmail.com,fathallah.houssem@gmail.com
  crash_mails_alert: fathallah.houssem@gmail.com,fathallah.houssem@gmail.com
  contacts_mail_alert: fathallah.houssem@gmail.com,fathallah.houssem@gmail.com
  account_expires_requests_mails_alert: fathallah.houssem@gmail.com,fathallah.houssem@gmail.com
  offer_basic_price: 10
  supported_countries: TN,FR


storage: &storage
  root: /home/hassenfath/www/b24/

development:
  storage:
    <<: *storage
  secret_key_base: 3623ea0e3aa3ee2031670dc24c5eb71b2e1fe7cef3d7921095bf4d4d4ddb2167d51f005f217a5b9838cc8981597f78a9864e06cca87e231ba3515fb550765f80
  <<: *smtp_dev_test
  admin:
    username: houssemFat
    password: Primos0902__1
    email: fathallah.houssem@gmail.com
  business_system:
    <<: *business_configure_dev_test
  geocoder:
    api_key : AIzaSyBSQlR8N3tgIHU4u6HD0Rzg5lRf_xynJZ8

test:
  storage:
    <<: *storage
  secret_key_base: 91d7d569273253f184444c872f354388e5d303fa8f3a863eb962a3c2101e3a5596c9b1fe2d435d2650d144b5d13d45f85c18c64e980e48ee56dce40125e946a5
  <<: *smtp_dev_test
  admin:
    username: houssemFat
    password: Primos0902__
    email: fathallah.houssem@gmail.com
  business_system:
    <<: *business_configure_dev_test
  geocoder:
      api_key : AIzaSyBSQlR8N3tgIHU4u6HD0Rzg5lRf_xynJZ8


# Run staging as production
staging:
  storage:
    <<: *storage
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  admin:
     username: <%= ENV["ADMIN_USERNAME"] %>
     password: <%= ENV["ADMIN_PASSWORD"] %>
     email: <%= ENV["ADMIN_EMAIL"] %>
  business_system:
    business_requests_mail_alert: <%= ENV["BUSINESS_REQUESTS_MAIL_ALERT"] %>
    crash_mails_alert: <%= ENV["CRASH_MAILS_ALERT"] %>
    contacts_mail_alert: <%= ENV["CONTACTS_MAIL_ALERT"] %>
    account_expires_requests_mails_alert: <%= ENV["ACCOUNT_EXPIRES_REQUESTS_MAILS_ALERT"] %>
    offer_basic_price: <%= ENV["OFFER_BASIC_PRICE"] %>
    supported_countries: <%= ENV["SUPPORTED_COUNTRIES"] %>
  geocoder:
      api_key : <%= ENV["GEOCODER_MAP_API_KEY"] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *storage
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>


